version: '2.0'

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 876:80
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/udp
      - 8853:8863/udp
      - 5443:5443/tcp
      - 5443/5443/udp
      - 3000:3000/tcp
    volumes:
      - /media/storage/system/docker/adguardhome/work:/opt/adguardhome/work
      - /media/storage/system/docker/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
