version: '2.0'

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jlesage/nginx-proxy-manager
    environment:
      - TZ=Europe/Moscow
    ports:
      - 8181:8181
      - 8080:8080
      - 4443:4443
    volumes:
      - /media/storage/system/docker/nginx-proxy-manager:/config:rw
    restart: unless-stopped
