version: '2.0'

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /media/storage/system/docker/sonarr:/config
      - /media/storage/media:/media/storage/media
    ports:
      - 878:8989
    restart: unless-stopped
