version: '2.0'

services:
  homeassistant:
    container_name: homeassistant
    restart: always
    image: homeassistant/home-assistant
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /media/storage/system/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /media/storage/system/docker/shared:/shared
    ports:
      - "891:8123"
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow