version: '2.0'

services:
  openvpn-client:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
      - net_admin
    environment:
      TZ: 'Europe/Moscow'
      Furewall: 'true'
      DNS: '192.168.1.160'
      DEFAULT_GATEWAY: 'false'
      Privileged: 'true'
    network_mode: bridge
    ports:
      - 9117:9117/tcp
    restart: unless-stopped
    volumes:
      - /media/storage/system/docker/openvpn-client/:/vpn:rw,slave
    devices:
    - /dev/net/tun:/dev/net/tun
