version: "2.1"
services:
  raneto:
    image: lscr.io/linuxserver/raneto
    container_name: raneto
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /media/storage/system/docker/raneto/config:/config
    ports:
      - 3100:3000
    restart: unless-stopped