version: '2.0'

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /media/storage/system/docker/jellyfin:/config
      - /media/storage/media:/data
      - /media/storage/photo:/photo
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped