version: '2.0'

services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    depends_on:
      - openvpn-client
    environment:
      TZ: 'Europe/Moscow'
      PUID: '1000'
      PGID: '1000'
    network_mode: "service:openvpn-client"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /media/storage/system/docker/jackett/blackhole/:/downloads:rw,slave
      - /media/storage/system/docker/jackett:/config:rw,slave
  
  openvpn-client:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
      - net_admin
    environment:
      TZ: 'Europe/Moscow'
      Furewall: 'true'
      DNS: '192.168.1.160'
      DEFAULT_GATEWAY: 'false'
      Privileged: 'true'
    network_mode: bridge
    ports:
      - 9117:9117/tcp
    restart: unless-stopped
    volumes:
      - /media/storage/system/docker/openvpn-client/:/vpn:rw,slave
    devices:
    - /dev/net/tun:/dev/net/tun
